// Pak Spotlight Worker — Cloudflare AI (primary)
var SUPABASE_URL = "https://supabase.co", SUPABASE_PUBLISHABLE_KEY = "sb_publishable_fkK2ryuBKr0WK96m34Cczg_7ofQBaOk", YOUTUBE_HANDLE = "@pkspotlight";
const DEFAULT_CATEGORIES = ["Serial / Series", "Long Play", "Comedy", "Shorts"], AI_CACHE_URL = `${SUPABASE_URL}/storage/v1/object/public/thumbnails/config/ai-cache.json`, AI_CACHE_SAVE_URL = `${SUPABASE_URL}/storage/v1/object/thumbnails/config/ai-cache.json`, CORS_HEADERS = { "access-control-allow-origin": "*", "access-control-allow-methods": "GET, POST, OPTIONS", "access-control-allow-headers": "authorization, content-type" }, ctxRef = { waitUntil: null };
let aiCacheMem = null;
function json(d, s = 200) { return new Response(JSON.stringify(d), { status: s, headers: { "content-type": "application/json; charset=utf-8", "cache-control": "no-store", ...CORS_HEADERS } }); }
function getBearer(r) { let h = r.headers.get("authorization") || ""; return h.startsWith("Bearer ") ? h.slice(7) : ""; }
async function requireUser(r) { let t = getBearer(r); if (!t) return { error: "Admin session required." }; let rs = await fetch(`${SUPABASE_URL}/auth/v1/user`, { headers: { apikey: SUPABASE_PUBLISHABLE_KEY, authorization: `Bearer ${t}` } }); return rs.ok ? { user: await rs.json(), token: t } : { error: "Invalid admin session." }; }
function cacheKeyForTitle(t) { return String(t || "").toLowerCase().replace(/\s*\|\s*.*$/, "").replace(/\s*-\s*(ptv|pak spotlight|classic|full|drama).*$/i, "").replace(/\b(ep|episode|part|qist|hissa)\s*\d+\b/gi, "").replace(/[^a-z0-9\u0600-\u06FF ]/gi, " ").replace(/\s+/g, " ").trim().slice(0, 80); }
function parseEpisodeNumber(t, d) { let m = `${t||""} ${d||""}`.match(/\b(?:ep|episode|part|qist|his+a?)\s*\.?\s*#?\s*(\d{1,3})\b/i) || String(t||"").match(/[(\[]\s*(\d{1,2})\s*[)\]]\s*$/) || String(t||"").match(/\s(\d{1,2})\s*$/); if (!m) return ""; let n = Number(m[1]); return n > 0 && n < 500 ? String(n) : ""; }
function cleanDramaTitle(t) { return String(t || "").replace(/\s*\|\s*.*$/, "").replace(/\s*-\s*(PTV|Pak Spotlight|Classic|Full|Drama|Play|HD).*$/i, "").replace(/\s*\b(Ep|Episode|Part|Qist|His+a?)\s*\.?\s*#?\s*\d+\b.*$/i, "").replace(/\s*[(\[]\s*\d{1,3}\s*[)\]]\s*$/i, "").replace(/\s*[-–—:]+\s*$/, "").replace(/\s+/g, " ").trim(); }
async function getCategories(e) { try { let r = await fetch(`${SUPABASE_URL}/storage/v1/object/public/thumbnails/config/categories.json?t=${Date.now()}`); if (r.ok) { let l = await r.json(); if (Array.isArray(l) && l.length > 0) return l.map(x => String(x || "").trim()).filter(Boolean); } } catch {} return DEFAULT_CATEGORIES; }
async function getFeaturedIds(e) { try { let r = await fetch(`${SUPABASE_URL}/storage/v1/object/public/thumbnails/config/featured.json?t=${Date.now()}`); if (r.ok) { let l = await r.json(); if (Array.isArray(l)) return l.map(x => Number(x)).filter(n => !isNaN(n) && n > 0); } } catch {} return []; }
async function getAiCache() { if (aiCacheMem) return aiCacheMem; try { let r = await fetch(`${AI_CACHE_URL}?t=${Date.now()}`); if (r.ok) { let d = await r.json(); if (d && typeof d === "object" && !Array.isArray(d)) { aiCacheMem = d; return aiCacheMem; } } } catch {} aiCacheMem = {}; return aiCacheMem; }
async function saveAiCacheEntry(k, f, t) { try { let c = await getAiCache(); c[k] = { ...f, _cachedAt: new Date().toISOString() }; let ks = Object.keys(c); if (ks.length > 300) ks.slice(0, ks.length - 300).forEach(x => delete c[x]); aiCacheMem = c; if (!t) return; await fetch(AI_CACHE_SAVE_URL, { method: "POST", headers: { apikey: SUPABASE_PUBLISHABLE_KEY, authorization: `Bearer ${t}`, "content-type": "application/json", "x-upsert": "true" }, body: JSON.stringify(c) }); } catch {} }
function videoId(v) { try { let s = String(v || "").trim(); if (s.includes("youtu.be")) return s.split("/").filter(Boolean).pop() || ""; if (s.includes("youtube.com")) { let u = new URL(s); if (u.pathname === "/watch") return u.searchParams.get("v") || ""; if (u.pathname.startsWith("/shorts/") || u.pathname.startsWith("/embed/")) return u.pathname.split("/").filter(Boolean)[1] || ""; } } catch {} let m = String(v || "").match(/[A-Za-z0-9_-]{11}/); return m ? m[0] : ""; }
async function youtubeJson(p, env) { if (!env.YOUTUBE_API_KEY) throw new Error("YOUTUBE_API_KEY unconfigured."); let u = new URL(`https://googleapis.com{p}`); u.searchParams.set("key", env.YOUTUBE_API_KEY); let r = await fetch(u), d = await r.json(); if (!r.ok || d.error) throw new Error(d.error?.message || "YouTube API error."); return d; }
async function channelId(env) { try { let d = await youtubeJson(`channels?part=id&forHandle=${encodeURIComponent(YOUTUBE_HANDLE)}`, env); return d.items?.[0]?.id || ""; } catch { return ""; } }
async function identifyVideo(url, env) { let id = videoId(url); if (!id) throw new Error("Invalid YouTube URL."); let d = await youtubeJson(`videos?part=snippet,contentDetails&id=${encodeURIComponent(id)}`, env), item = d.items?.[0]; if (!item) throw new Error("Video not found."); let th = item.snippet?.thumbnails || {}; return { id: item.id, title: item.snippet?.title || "", description: item.snippet?.description || "", publishedAt: item.snippet?.publishedAt || "", channelId: item.snippet?.channelId || "", channelTitle: item.snippet?.channelTitle || "", thumbnail: th.maxres?.url || th.standard?.url || th.high?.url || th.medium?.url || th.default?.url || `https://ytimg.com{id}/hqdefault.jpg`, duration: item.contentDetails?.duration || "" }; }
function playlistIdFromUrl(v) { let s = String(v || "").trim(); try { let u = new URL(s), p = u.searchParams.get("list"); if (p) return p; } catch {} let m = s.match(/(?:^|[^A-Za-z0-9_-])(PL[A-Za-z0-9_-]{10,}|UU[A-Za-z0-9_-]{10,}|[A-Za-z0-9_-]{13,})/); return m ? m[1] : ""; }
async function fetchPlaylistMeta(pid, env) { let d = await youtubeJson(`playlists?part=snippet,contentDetails&id=${encodeURIComponent(pid)}`, env), item = d.items?.[0]; if (!item) throw new Error("Playlist not found."); return { id: pid, title: item.snippet?.title || "Playlist", description: item.snippet?.description || "", count: item.contentDetails?.itemCount || 0, thumbnail: item.snippet?.thumbnails?.high?.url || "" }; }
async function fetchPlaylistItems(pid, env, max = 50) { let items = [], token = ""; while (items.length < max) { let p = `playlistItems?part=snippet,contentDetails&maxResults=${Math.min(50, max - items.length)}&playlistId=${encodeURIComponent(pid)}`; if (token) p += `&pageToken=${encodeURIComponent(token)}`; let d = await youtubeJson(p, env); for (let it of d.items || []) { let vid = it.snippet?.resourceId?.videoId || ""; if (!vid) continue; let th = it.snippet?.thumbnails || {}; items.push({ id: vid, title: it.snippet?.title || "", description: it.snippet?.description || "", publishedAt: it.snippet?.publishedAt || "", thumbnail: th.high?.url || th.medium?.url || `https://ytimg.com{vid}/hqdefault.jpg`, url: `https://youtube.com{vid}` }); } token = d.nextPageToken || ""; if (!token) break; } return items; }
function supaRest(p, t, o = {}) { return fetch(`${SUPABASE_URL}/rest/v1/${p}`, { ...o, headers: { apikey: SUPABASE_PUBLISHABLE_KEY, authorization: `Bearer ${t}`, "content-type": "application/json", ...(o.headers || {}) } }); }

async function aiAutofill(video, env, opts = {}) {
  let allowed = await getCategories(env), catStr = allowed.join(", "), tkn = opts.authToken || "", base = cleanDramaTitle(video.title), key = cacheKeyForTitle(video.title);
  if (!opts.skipCache && key) { try { let c = await getAiCache(), hit = c[key]; if (hit && hit.title) { let ep = parseEpisodeNumber(video.title, video.description); return { video, cached: true, fields: { title: ep && hit.series_name ? `${hit.title.replace(/\s*\b(Ep|Episode|Part)\s*\d+.*$/i, "")} Ep ${ep}` : hit.title, urdu_title: hit.urdu_title || "", year: hit.year || String(video.publishedAt || "").slice(0,4), type: hit.type || allowed[0], series_name: hit.series_name || base, episode_number: ep || hit.episode_number || "", writer: hit.writer || "", director: hit.director || "", produced: hit.produced || "", cast: hit.cast || "", description: hit.description || video.description.slice(0,500), seo_title: hit.seo_title || "", seo_description: hit.seo_description || "", thumbnail: video.thumbnail } }; } } catch {} }
  let prompt = `Return ONLY JSON object, no markdown chat conversation formatting. PTV drama metadata profiles. Input Title: ${video.title}. Description: ${video.description.slice(0,2000)}. Allowed categories list: ${catStr}. Keys required: title, urdu_title, year, type, series_name, episode_number, writer, director, produced, cast, description.`;
  let raw = "";
  if (env.AI) { try { let res = await env.AI.run("@cf/meta/llama-3.1-8b-instruct", { messages: [{ role: "system", content: "Return ONLY valid raw JSON metadata structures." }, { role: "user", content: prompt }], temperature: 0.2, max_tokens: 1024 }); raw = (res?.result?.response || res?.response || "").trim(); } catch {} }
  if (!raw) throw new Error("Cloudflare AI computation failure.");
  let out = {}; try { out = JSON.parse(raw); } catch (e) { let s = raw.indexOf("{"), eIdx = raw.lastIndexOf("}"); if (s >= 0 && eIdx > s) try { out = JSON.parse(raw.slice(s, eIdx + 1)); } catch {} }
  if (!out.title) throw new Error("AI structure parsing error.");
